### PR TITLE
Don't install torch in firedrake-parmmg image

### PR DESCRIPTION
**Pull request by ddundo**
As mentioned in https://github.com/mesh-adaptation/UM2N/issues/9, I'd like to have pytorch on a GPU in a Docker container. I wanted to keep it minimal for now before I get it working so I didn't install UM2N for now. It's already a big image so I thought we could just provide the Dockerfile for users to build it locally, instead of building it and pushing it ourselves to ghcr.io.

Firedrake has an option to install pytorch with CUDA with its install script by passing `--torch cuda` instead of just `--torch`. I tested this and found that it doesn't install all dependencies so I went with the `pip3 install torch torchvision torchaudio` option which works.

~~Building the `Dockerfile.firedrake-cuda` image succeeds and I am able to run it normally with `docker run -it firedrake-cuda-image`. But running it with `docker run --gpus=all -it firedrake-cuda-image` gives an error:~~
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/8e6946a15b79c2644e363173114088fbc81ac236a411ff1092ec26696eeb779b/merged/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file exists: unknown.
```

~~I googled and people point out to issues on the host machine, e.g. here https://github.com/NVIDIA/nvidia-docker/issues/1648#issuecomment-1161813687 . However, I am able to run, for example, this `docker run -it --gpus=all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi` which then returns~~
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.02              Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti     On  |   00000000:01:00.0  On |                  N/A |
|  0%   40C    P8             19W /  220W |     755MiB /   8192MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A        31      G   /Xwayland                                   N/A      |
|    0   N/A  N/A        35      G   /Xwayland                                   N/A      |
+-----------------------------------------------------------------------------------------+
```
~~which also shows that my GPU is in persistence mode.~~

~~@chunyang-w you set up a Dockerfile with CPU support, so I don't know if this is of interest to you. If it is, do you know what the issue could be? Or could you please try building this locally and see if you get the same error? I would like to see if it really is a host machine problem or if I need to do something else in the image :)~~

~~Edit: or @jwallwork23 if you've got time and think this would be worth having :)~~

Edit2: Sorry, see comment below

### CODE REVIEW

**Comment by ddundo** [comment]
@jwallwork23 @chunyang-w Sorry, I found the issue. The issue is that a GPU isn't available during `docker build`.

This simple solution works:
1. ` docker run --gpus=all -it ghcr.io/mesh-adaptation/firedrake-parmmg:latest`
2. Inside the container do:
   -  `source firedrake/bin/activate`
   - `pip uninstall torch`
   - `pip3 install torch torchvision torchaudio`

which then installs pytorch with CUDA. So that's great!

Now, we could add `pip3 install torch torchvision torchaudio` in a Dockerfile, but this will only install CUDA stuff properly if a GPU is available during `docker build`. I googled and there are non-trivial ways to achieve this. I see that github also has [runners with GPUs](https://github.blog/changelog/2024-07-08-github-actions-gpu-hosted-runners-are-now-generally-available/) so we could probably rework `reusable_docker_build.yml` to have access to a GPU when it's building the UM2N image.

But that's probably more complicated than we need. I think the following would be just fine:

1. We don't install torch in `Dockerfile.firedrake` (i.e. remove the line `--torch`)
2. We don't have a specific docker image for UM2N, but instead...
3. Add a Makefile in UM2N similar to other repos, so that we can install UM2N and pytorch with `make install`
4. Make it clear in the UM2N install instructions that if you want GPU support and Pytorch with CUDA, that you need to add `--gpus=all` to `docker run`. Otherwise it will install Pytorch with CPU support

What do you think?

**Comment by ddundo** [comment]
Not installing torch also reduces image size by 900MB (10%) :)

**Comment by ddundo** [comment]
Thanks @jwallwork23, that makes sense. I changed this PR to only remove `--torch` in `Dockerfile.firedrake` since we don't need it outside of UM2N - and will install it and other dependencies for UM2N anyway.

I will then leave the UM2N Dockerfile business you suggested to @chunyang-w since he started it already. Also happy to take over :)

**Review by jwallwork23 — APPROVED** [review]
Sounds good, thanks for looking into this @ddundo.

**Pull request merged**
